name: first-actions-pipeline
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-secondjob-step
        run: echo "Second Job"
